### ISSUE TITLE
[HGS] feature requests: teams and syntax additions

### ISSUE THREAD

**Issue by aleislost** [Agma-Schwa/nguh.org#3]
1. Request to add a syntax code for was/were, in cases of a tribute being a group of entities instead of just one
2. Request for the implementation of teams or houses into the game, so tributes of the same team can't kill each other and for other stuff. Along with team names and colors if possible 

Thanks a bunch, been having a lot of fun with the simulator!

**Comment by Sirraide** [comment]
> 1. Request to add a syntax code for was/were, in cases of a tribute being a group of entities instead of just one

Sure, I can add `%w` as a format specifier.

> 2. Request for the implementation of teams or houses into the game, so tributes of the same team can't kill each other and for other stuff. Along with team names and colors if possible

That one is a lot more complicated; I don’t think I’ll be implementing that any time soon, but if someone else wants to go ahead and add it, I wouldn’t be opposed.

**Comment by Sirraide** [comment]
1. has been added in 59eb325; I’ll move 2 to a separate issue.
